project:
  type: book
  output-dir: docs

book:
  title: "Statistics Minus the Math (2e)"
  author: "Nathan Favero"
  date: "2/25/2026"
  chapters:
    - index.qmd
    - part: "Data Essentials"
      chapters:
      - getting-started.qmd
      - describing-one-variable.qmd
      - correlation.qmd
      - qual-associations.qmd
      - stat-inference.qmd
      - h-tests.qmd
    - part: "Going Deeper with Data"
      chapters:
      - prob-models.qmd
      - sampling-distributions.qmd
      - causality.qmd
      - measurement.qmd
      - regression.qmd
#      - practical-points.qmd
    - teaching-resources.qmd
    - change-log.qmd

#bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
      dark: superhero
  pdf:
    documentclass: scrreprt
    header-includes: |
      \publishers{Get the latest version of this text at: \url{https://minusthemath.com} \bigskip \bigskip \bigskip \bigskip \\
      \href{https://creativecommons.org/licenses/by-nc-nd/4.0/}{\includegraphics{Images/by-nc-nd.png}}}
