# Artificial Intelligence and Machine Learning {#sec-ai}

\[***Working draft notes for instructors**: This is a rather early stage draft of the chapter but gives you a sense of what I am aiming to cover.*\]

Statistical models are the underlying machinery powering many AI tools. The models powering AI are extremely complicated, so they cannot be covered in full detail here. Still, several important observations about how AI works will be described in this chapter, building from concepts we have learned throughout this book.

The landscape of AI technology is rapidly developing, so by the time you are reading this there may be many new advances beyond what is covered in this chapter. While it is always difficult to predict the future, I expect the concepts and modeling approaches covered here will nonetheless remain relevant for many years to come. What this chapter cannot do, however, is tell you exactly how society, science, or the practice of statistics may look in 2035 or 2030, compared to 2026---the year in which I am writing this. Rather than trying to predict the future, I will focus on describing technologies that have been crucial to recent developments in AI, as well as some of the ways in which people are already starting to change how the practice statistics, research, and study.

## Machine Learning

Most AI tools in some way rely on **machine learning** methods---a broad range of techniques used to develop a model based on patterns found in existing data, with the intent to then apply this model to future data inputs (independent variables) and provide useful predictions or related outputs (dependent variables). Some machine learning techniques have existed for decades, but their use expanded widely during the past decade or two as computational advances dramatically increased possibilities for deploying them productively.

Machine learning techniques vary widely, but they usually are designed to allow for estimating very flexible models. For example, they are often built to allow for detecting and incorporating various nonlinearities, much like one can do by adding polynomials or interaction terms to a linear regression, as we learned about in the prior chapter. Typically, incorporating many nonlinearities in a flexible manner will require estimating a rather complicated model.

What do we mean by complicated? Consider the relatively simple model with an interaction term that was described in the prior chapter. It required estimating just four parameters (coefficients), as indicated by four different $\beta$’s in the following equation (note that in the prior chapter, the equation was written to show the actual estimates for these parameters):

$$\widehat{UGPA}_i = \beta_0 + \beta_1 \times HSGPA_i + \beta_2 \times SAT_i + \beta_3 \times HSGPA_i \times SAT_i$$

It is not unusual in social science research papers to find more complicated linear regression models that contain 10 or 20 parameters. It is even common in certain areas of social science to encounter studies using regression models (e.g., “high-dimensional fixed effects” models) that contain hundreds or thousands of parameters, most of which are not directly interpreted (or even reported) in a research report but which allow for adjustments behind the scenes that can help researchers obtain better estimates for coefficients corresponding to variables of interest.

Even these rather large regression models look tiny in a machine learning context. Relatively simple machine learning models often contain thousands or even millions of parameters. GPT-3, the precursor to the original ChatGPT model that was release in November 2022, has 175 billion parameters! Today’s models are even larger.

Indeed, one of the distinguishing features of many machine learning techniques (compared to traditional statistical models) is that they enable developing models with a huge number of parameters. Under the right circumstances, such models can yield stunning results. Consider “classifier” models that predict what category an observation belongs to. If each observation in the relevant dataset is an image of a single animal, the classifier might be able to tell us what animal appears in the image. How does it accomplish that? The machine representation of the image (telling us the color of each pixel in the image) is processed through a very complicated equation (or series of equations) with many parameters. A rather generic (but large) model structure can then be used to develop a model for a specific task, such as the animal classification task described above. In order to do this, one will need a very large dataset of animal pictures that is already labeled with the name of the animal. The model is created or “trained” from this initial dataset, and then new images (with no label for what they are depicting) can be fed into the model, and it will provide an estimation of what animal is depicted in each new image. Practice has shown that for many complex problems, machine learning techniques can be used to generate remarkably accurate pattern recognition algorithms with little guidance from humans on what patterns to look for. Instead of relying on specific guidance from humans, the models are developed through what is essentially a very long and repeated process of trial and error with a very large dataset that is already marked with correct answers.

A highly complex equation (or set of equations) will indicate precisely how the model translates inputs into outputs. For example, the parameters will indicate how the pixels in the image are translated into a prediction about the animal being depicted, but these equations will generally be far too large and complicated for a human to examine them directly. Instead, many machine learning models are considered to be essentially “black boxes,” meaning it is difficult to peer inside them and know precisely why they are producing the predictions they are outputting. Instead, description of machine learning models often focuses on describing their performance. There are many measures of model performance that lie beyond the scope of this text, but some of the simplest ones might simply report the percentage of images that are correctly classified in a “testing dataset” that was not used to train the model.

In the world of machine learning, we typically refer to the data used to train a model as **training data**. Many machine learning models require huge training datasets, and developers have resorted to some pretty clever methods for obtaining training data. When you visit a webpage,and it asks for you to prove you are a human by clicking on images of certain things (or typing out the text shown in a distorted image), you may be helping to create training data for a machine learning model.

One of the key challenges that machine learning techniques confront is **overfitting**. Overfitting occurs whenever a model is tailored so finely to patterns in a training dataset that it is picking up on peculiarities that will not generalize to other data (beyond the training data). This is also a concept and concern that appears in traditional statistical methods, particularly in the context of using statistical models for prediction.

### Important Principles of Machine Learning

While several technological innovations were required to enable the development of ChatGPT, development of current AI models still follows some important principles that have long been known to users of machine learning techniques.

First, tons of data is needed to effectively develop complicated machine learning models. The concept of “degrees of freedom,” introduced in @sec-sampling-distributions, helps to explain why. In traditional statistics, we often measure sample size in the form of degrees of freedom, which is found by subtracting the number of model parameters from the number of observations (df = n – m, where m is the number of parameters). We can think of degrees of freedom as describing our effective sample size---how much information we are getting to help us determine the values of our parameter estimates. A simple regression model with 10 parameters might be somewhat reasonably estimated with 100 observations (although not very precisely), since there will be 90 degrees of freedom (df = 100 – 10 = 90). By extension, a model with 1 million parameters is going to require a dataset with well over a million observations in order to be estimated at all, at least with traditional statistical techniques. In practice, the world of machine learning is more complicated and we cannot necessarily apply the concept of degrees of freedom in the same way. But what does carry over from traditional statistics is the general conclusion that models with huge numbers of parameters will require huge datasets to develop the models.

A second key principle from machine learning is that the quality (not just the quantity) of training data really matters to model performance. Specifically, we want training data that covers as wide a variety of circumstances as possible. A model trained on data that differs markedly from the data on which it is ultimately deployed will often break down. For example, if a classifier is built from professionally-shot photographs of animals, it may not work so well with amateur photographs, which may be much less clear. Another concern is that the training data may provide biased or distorted patterns. For example, if all images of snow leopards in a training dataset show these animals in their natural habitat of a snow-ridden landscape, the classifier may start classifying these animals based on the background rather than the features of the animals themselves.

A third key principle is that many machine learning techniques are fairly “black box,” meaning that they detect patterns in the data in ways that make it difficult to determine an exact mapping of inputs to outputs. The reasons for this are related to the previously-mentioned fact that many machine learning models have dizzying numbers of parameters: with so many parameters, very complex equations will describe how inputs relate to outputs, and there will typically be no simple way to describe how changing one inputs changes the prediction. This principle also helps to explain some of the problems of poor classification that can easily arise from poor training data, as mentioned in the prior principle. For example, if animal photos are being classified by their background, this might go unnoticed precisely because there is not transparency into what is making the classifier work well under certain conditions (i.e., with certain data). Many efforts have been made to help improve the interpretability of machine learning models, and these techniques often can be used to help us get some sense of how inputs map to outputs in the models. However, because the models themselves are so complicated, it will typically be impossible to fully understand or interpret them. Furthermore, it is incumbent upon the developers and users of the models to be sure that they have been examined and scrutinized in ways that enable responsible use of the models. What that means in practice will depend on the purpose for which the models are being deployed. If they are used to help radiologists interpret medical scans or inform decisions in the criminal justice system (e.g., length of prison sentences), we probably want models that have been thoroughly scrutinized for potential problems or unintended behaviors. If the models are being used in a more experimental or exploratory way (e.g., predicting what products may be of interest to a potential customer based on their profile), they may require fewer checks.

A fourth principle is that accurate **extrapolation** is extremely difficult. Extrapolation refers to making predictions outside the range of the observed data. For example, if a training dataset uses age to help predict an outcome but only contains individuals between the ages of 18 and 65, extrapolation would refer to making predictions about people younger than 18 or older than 65. Extrapolation often results in bad predictions, in part because it is impossible to know (at least from the observed data) what nonlinearities might exist outside the range of the observed values.

### Uses of Machine Learning in Research

Machine learning techniques are being employed more and more often by researchers. However, they have not displaced traditional statistical methods and are unlikely to do so any time soon. That is in part due to the black box nature of many machine learning models, as well as the fact that machine learning usually emphasizes prediction rather than explanation. Because social science researchers often care about causality, they often prefer working with relatively simple models that also allow for simple interpretations of how independent variables are linked to dependent variables. These models may oversimplify reality (e.g., by assuming linear relationships) and yield less accurate predictions than machine learning methods, but they may still allow social scientists to better assess their explanatory research questions. It is difficult to predict the future, though, and some researchers advocate for wider use of machine learning techniques, even for explanatory or causal research. Especially when it comes to estimating average treatment effects based on experiments, very simple statistical techniques have been shown to be well-suited for analysis. Thus, it is hard to see why such methods would be displaced in favor of something more complicated. For other types of studies, though, it is harder to assess how future researchers will weigh the benefits and costs of ever-evolving machine learning techniques for helping to answer research questions.

## Large Language Models

As of 2026 when I am writing this, when most people hear about AI, they are probably thinking of technologies like ChatGPT that are large language models (LLMs). LLMS are rooted in word prediction algorithms. You can think of an LLM as being driven by an algorithm that simply tries to predict the next word in a conversation and then continues filling in new words until entire sentences and even paragraphs have been written. Simple word prediction algorithms had to be modified in several ways, though, to allow for the coherent paragraphs we now find coming out of LLMs. One of these innovations was to essentially modify the equations used to predict the next word to predict not just a single next word but to also have a prediction about an overarching parameter (which we might think of as a “theme”) that would guide the coming individual words.

The world was stunned by the many possibilities of LLMs that immediately were apparent with the release of ChatGPT. More recent developments in LLMs have only improved upon these capabilities. Especially when it comes to programming tasks, LLMs have yielded stunning results.

I will highlight several aspects of how LLMs function that are useful to know about:

1.  LLMs simulate conversations. You can think of LLMs as generating synthetic conversations (sometimes with a human as a live participant), based on huge volumes of prior conversations (and other text data) that they have been trained on. The conversations of the LLMs will generally contain more text than what you observe in a chat window. In addition to whatever prompt you feed into a chatbot, there will generally be a “system prompt” with generic instructions to the chatbot that are also a part of the synthetic conversation. The bot may also have an “internal conversation” that is not displayed to you prior to refining exact text to display in response to your prompt. These are just some examples of clever ways that LLM developers have found to improve the quality of LLMs through use of additional text in the synthetic conversation beyond what is displayed to the user.
2.  LLMs are designed to be somewhat noisy and unpredictable.
3.  LLMs often display “jagged intelligence.”
4.  Specific LLMs vary widely from one another.
5.  LLMs can be integrated with various other tools and algorithms.
6.  LLMs can be applied to things other than just language.
