# Change Log {#sec-change-log .unnumbered}

<!-- This version (1.3) was updated July 31, 2024. -->

PDFs of past versions are currently available at <https://github.com/favero-nate/minus-the-math/tree/main/past_versions>

-   Version 2.0: This second edition is heavily revised. Coverage of topics by chapter often changes, as shown in the table below. Exercises have been added to the end of each chapter.

    | 2nd edition | 1st edition |
    |----------------------------------------------|--------------------------|
    | Ch. 1 (data structures & a bit of graphing) | most of Ch. 1 |
    | Ch. 2 (describing one variable at a time) | Ch. 2; a bit of Ch. 1 (percentiles & boxplots) |
    | Ch. 3 (bivariate relationships - quantitative variables) | Ch. 3 |
    | Ch. 4 (bivariate relationship involving qualitative variables) | Ch. 12-13; some material in Ch. 1 (bivariate graphs) & Ch. 9 (interpreting contingency tables) |
    | Ch. 5 (statistical inference) | Ch. 4 |
    | Ch. 6 (hypothesis testing) | parts of Ch. 7-9 |
    | Ch. 7 (probabilistic models) | Ch. 5 & 11 |
    | Ch. 8 (sampling distributions) | Ch. 6; a bit of Ch. 7 (z/t tests for a single mean or regression slope) |
    | Ch. 9 (research design and causality) | mostly not covered; Ch. 10 |
    | Ch. 10 (measurement) | not covered |
    | Ch. 11 (regression models) | not covered |

    : Mapping of topics across editions

-   Version 1.4 updates: Minor edits to improve clarity and fix typos (most importantly in Ch. 13, where the wrong variable value was referenced several times). Page numbering in PDF should remain essentially intact.

-   Version 1.3 updates: New material on multiple regression (ends of Ch. 3, 4, 6, and 7). Expanded discussion of confidence intervals (Ch. 4), including new section on interpreting confidence intervals. Expanded discussion of ANOVA (end of Ch. 8) and of contingency tables (Ch. 9). Notation updated in line with conventions: regression parameters are redone, and $\bar{X}$ is now used for the sample mean and $n$ for sample size. Slight extension of section on the standard normal distribution. Section on degrees of freedom moved to an appendix (end of Ch. 6). Various formatting updates (book was recreated using Quarto) and minor (mostly non-substantive) edits throughout.

-   Version 1.2 updates: The discussion of transforming variables now appears in Ch. 2 (rather than Ch. 3).
