# Teaching Resources {#sec-teaching-resources .unnumbered}

If you're using this text, I'd love to know. You can fill out this brief form (<https://forms.gle/qBUFdb4vEuDUkzBu6>), where you can also sign up to receive emails when I post updated versions or related materials.

## Answers to Exercises

Please email me (find my address at <https://nathanfavero.com>) from your institutional email address to request an answer key. I may ask for verification that you are a course instructor.

## Stata/R Labs

I've created a number of Stata and R labs that I use when I teach. There are also some handouts, including a couple covering Excel. Such resources are available here: <https://github.com/favero-nate/minus-the-math/tree/main/labs>

## Lecture Slides/Videos

While they do not directly correspond to this version of the text, there are some (Stata-based) lecture slides and videos I created to use alongside this book when I teach. They are currently available here: <https://github.com/favero-nate/minus-the-math/tree/main/lecture_slides>

## A Few More Ways this Book is Unique

Beyond the initial list provided in the book's preface, I highlight here some additional unique aspects of this text that may be of particular interest to instructors:

1.  My own assessment is that this text is compatible with the highly-regarded 2016 Guidelines for Assessment and Instruction in Statistics Education (GAISE) College Report, as well as the new guidance currently described in the ongoing revision that has yet to be finalized (<https://amstat.quarto.pub/college-gaise/>). Some of the guidelines go beyond what a textbook will directly cover, describing course pedagogy and assessment. Use of software/apps is also not embedded in this text, with the intent that instructors can choose the particular software that best matches their program needs. Please see the above-linked guidelines for ideas about how to best approach teaching a course that uses this book.

2.  Part one can stand alone as a guide to getting started with data in social science. These first six chapters cover data description and preview how inference tools are used in research. These chapters are therefore ideal for a short course or pairing with other materials for a course with a broader scope. For example, a research methods course might add materials covering research design, qualitative methods, theory building, and/or literature review. A data science course might instead add a book introducing a programming language used for data analysis.

3.  There is a bit of Stata code in one appendix (@sec-qual-associations), but otherwise all examples are presented apart from any statistical software package.

4.  The treatment of probability theory skips much of the typical material in favor of discussing probabilistic modeling, which I believe is far more relevant to quantitative social science. (I also note alignment here with the aforementioned GAISE College Reports, which have long recommended de-emphasis of probability theory in teaching college-level introductory statistics.)

5.  In addition to traditional statistical inference ideas that describe estimating parameters of population from a sample, I emphasize that we often use inference to draw conclusions about counterfactuals. This approach is informed by Kass (2011): <https://doi.org/10.1214%2F10-STS337>
