<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>2&nbsp; Describing One Variable at a Time – Statistics Minus the Math (2e)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./correlation.html" rel="next">
<link href="./getting-started.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-b758ccaa5987ceb1b75504551e579abf.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-70a47bd5681a7291082a5b9f83d58762.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-18279696052386181f2d5e2642aac360.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-70a47bd5681a7291082a5b9f83d58762.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./getting-started.html">Data Essentials</a></li><li class="breadcrumb-item"><a href="./describing-one-variable.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Describing One Variable at a Time</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistics Minus the Math (2e)</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Data Essentials</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./getting-started.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Getting Started with Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./describing-one-variable.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Describing One Variable at a Time</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Relationships Between Two Quantitative Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./qual-associations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Relationships with Qualitative Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Statistical Inference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./h-tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Going Deeper with Data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Probabilistic Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sampling-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Sampling Distributions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./causality.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Research Designs and Causality</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./measurement.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Measurement</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Regression Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ai.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Artificial Intelligence and Machine Learning</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./teaching-resources.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Teaching Resources</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./change-log.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Change Log</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#essential-terms-and-concepts-for-describing-quantitative-variables" id="toc-essential-terms-and-concepts-for-describing-quantitative-variables" class="nav-link active" data-scroll-target="#essential-terms-and-concepts-for-describing-quantitative-variables"><span class="header-section-number">2.1</span> Essential Terms and Concepts for Describing Quantitative Variables</a></li>
  <li><a href="#sec-percentiles-and-box-plots" id="toc-sec-percentiles-and-box-plots" class="nav-link" data-scroll-target="#sec-percentiles-and-box-plots"><span class="header-section-number">2.2</span> Percentiles and Box Plots</a>
  <ul class="collapse">
  <li><a href="#defining-percentiles" id="toc-defining-percentiles" class="nav-link" data-scroll-target="#defining-percentiles"><span class="header-section-number">2.2.1</span> Defining percentiles</a></li>
  <li><a href="#box-plots-and-five-number-summaries" id="toc-box-plots-and-five-number-summaries" class="nav-link" data-scroll-target="#box-plots-and-five-number-summaries"><span class="header-section-number">2.2.2</span> Box plots and five number summaries</a></li>
  </ul></li>
  <li><a href="#measures-of-central-tendency" id="toc-measures-of-central-tendency" class="nav-link" data-scroll-target="#measures-of-central-tendency"><span class="header-section-number">2.3</span> Measures of Central Tendency</a></li>
  <li><a href="#measures-of-spreaddescribing-one-variable-2" id="toc-measures-of-spreaddescribing-one-variable-2" class="nav-link" data-scroll-target="#measures-of-spreaddescribing-one-variable-2"><span class="header-section-number">2.4</span> Measures of Spread</a></li>
  <li><a href="#exercisesdescribing-one-variable-3" id="toc-exercisesdescribing-one-variable-3" class="nav-link" data-scroll-target="#exercisesdescribing-one-variable-3"><span class="header-section-number">2.5</span> Exercises</a></li>
  <li><a href="#sec-describing-one-variable-appendix-i-calculating-percentilesdescribing-one-variable-4" id="toc-sec-describing-one-variable-appendix-i-calculating-percentilesdescribing-one-variable-4" class="nav-link" data-scroll-target="#sec-describing-one-variable-appendix-i-calculating-percentilesdescribing-one-variable-4"><span>Chapter 2</span> Appendix I: Calculating Percentiles</a></li>
  <li><a href="#sec-describing-one-variable-appendix-ii-formulas-for-calculating-key-descriptive-statistics" id="toc-sec-describing-one-variable-appendix-ii-formulas-for-calculating-key-descriptive-statistics" class="nav-link" data-scroll-target="#sec-describing-one-variable-appendix-ii-formulas-for-calculating-key-descriptive-statistics"><span class="header-section-number">2.6</span> <span>Chapter 2</span> Appendix II: Formulas for Calculating Key Descriptive Statistics</a>
  <ul class="collapse">
  <li><a href="#meandescribing-one-variable-5" id="toc-meandescribing-one-variable-5" class="nav-link" data-scroll-target="#meandescribing-one-variable-5">Mean</a></li>
  <li><a href="#variancedescribing-one-variable-7" id="toc-variancedescribing-one-variable-7" class="nav-link" data-scroll-target="#variancedescribing-one-variable-7">Variance</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./getting-started.html">Data Essentials</a></li><li class="breadcrumb-item"><a href="./describing-one-variable.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Describing One Variable at a Time</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-describing-one-variable" class="quarto-section-identifier"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Describing One Variable at a Time</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>[<em><strong>Working draft notes for instructors</strong>: This is an early draft of this chapter, and while I expect the basic structure to remain, I am aware that the current examples (including the case study) are underdeveloped. They will be updated shortly (as of June 23, 2026). If you were looking at this in June, note that I have now (as of July 1) moved the section on variable transformations to the middle of Ch. 4.</em>]</p>
<p>This chapter introduces a variety of concepts and statistics that help us describe one variable at a time. We can describe variables using words, tables, and graphs. The prior chapter already introduced the use of graphs to depict a variable, so this chapter will mainly focus on explaining how to describe variables using words and tables. When we describe a single variable, we typically focus on the <strong>distribution</strong> of the variable. A distribution refers to how frequently all values of a variable occur. For example, if I am examining the binary variable sex in a dataset, the distribution might be 53% female and 47% male. For binary variables it is very easy to succinctly describe the distribution because there are only two possible values. By contrast, quantitative variables sometimes take on many more values than would make sense to list out in a sentence (or even a table), so a variety of terms and statistics have been developed to succinctly summarize the distributions of quantitative variables. As such, most of this chapter will focus on quantitative variables.</p>
<p>After introducing this chapter’s case study, the following sections will introduce key terms for describing a distribution, explain percentiles, describe measures of central tendency, and then cover measures of spread. Finally, the chapter will go over variable transformations, which can be used to change the units in which a variable is expressed.</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Chapter Case Study: A Survey of Nonprofit Organizations
</div>
</div>
<div class="callout-body-container callout-body">
<p>Some researchers wanted to learn about nonprofit organizations, so they created a survey and invited leaders of nonprofits in the U.S. to respond to it. The authors made efforts to ensure the final survey data included responses from a broad range of nonprofit organizations throughout the U.S., making it a particularly high quality source of information about the nonprofit sector. The researchers have made the data publicly available, although they mask certain details in order to anonymize the data (meaning that one should not be able to identify the exact nonprofit being described in a given observation).</p>
<p>There are many variables available in the nonprofit survey dataset, but we will look at only a handful in this chapter. To start, we can get a sense of the types of missions pursued by the nonprofits completing the survey by looking at a 5-category sub-sector variable provided by the researchers.</p>
<p><a href="#tbl-5-nonprofit-subsectors" class="quarto-xref">Table&nbsp;<span>2.1</span></a> is an example of <strong>frequency table</strong>, which lists all the values a variable takes on and how frequently each one occurs. Based on the frequencies shown, the category with the largest percentage is human services, so we can say that the <strong>mode</strong> of the sub-sector variable is “human services.” Since no category has more than 50%, there is no category that accounts for a majority of observations. Instead, we say that a <em>plurality</em> of organizations in this dataset belong to the human services sub-sector, meaning that it is the largest category but is still less than 50%.</p>
<div id="tbl-5-nonprofit-subsectors" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-5-nonprofit-subsectors-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2.1: Frequency Table for Sub-Sector Variable
</figcaption>
<div aria-describedby="tbl-5-nonprofit-subsectors-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Nonprofit Sub-Sector</th>
<th>Freq.</th>
<th>Percent</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Arts</td>
<td>862</td>
<td>21.25</td>
</tr>
<tr class="even">
<td>Education</td>
<td>220</td>
<td>5.42</td>
</tr>
<tr class="odd">
<td>Health</td>
<td>302</td>
<td>7.45</td>
</tr>
<tr class="even">
<td>Human Services</td>
<td>1,753</td>
<td>43.22</td>
</tr>
<tr class="odd">
<td>Other</td>
<td>919</td>
<td>22.66</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Total</td>
<td>4,056</td>
<td>100.00</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>How do these nonprofits fund their operations? There are multiple survey questions relevant to this topic, but let’s focus on an item asking about reliance on individual donations. Specifically, the item asks nonprofit leaders to estimate the percent of their revenue that comes from individual donations. <a href="#tbl-nonprofits-descriptive-stats" class="quarto-xref">Table&nbsp;<span>2.2</span></a> displays some typical statistics to describe this variable, alongside two other variables that we will also discuss. As the headings indicate, this table displays (for each variable) the number of observations (after excluding any observations with missing data for this variable), the mean (or average), the standard deviation, the minimum, and the maximum. The row labeled “% Rev.&nbsp;from Indv. Donations” displays these statistics for the individual donations variable. The number of observations is 2,672, which is notably smaller than the values listed for the other two variables, meaning that this variable has more missing values, probably because many respondents skipped answering this question (or perhaps quit the survey altogether before getting to this question). We also see that the nonprofit leaders in this dataset estimate they receive an average of 27% of their revenue from individual donations, though the minimum and maximum values also indicate the existence of organizations receiving no individual donations (0%) and receiving revenue only from individual donations (100%). The standard deviation is a more difficult statistic to interpret, so we will wait to describe it until later in this chapter.</p>
<div id="tbl-nonprofits-descriptive-stats" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-nonprofits-descriptive-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2.2: Descriptive Statistics for Quantitative Variables
</figcaption>
<div aria-describedby="tbl-nonprofits-descriptive-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 34%">
<col style="width: 10%">
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 10%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Obs.</th>
<th>Mean</th>
<th>Std. Dev.</th>
<th>Min</th>
<th>Max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>% Rev.&nbsp;from Indv. Donations</td>
<td>2672</td>
<td>27.0</td>
<td>28.7</td>
<td>0</td>
<td>100</td>
</tr>
<tr class="even">
<td># of Fulltime Staff</td>
<td>3529</td>
<td>14.4</td>
<td>58.6</td>
<td>0</td>
<td>1600</td>
</tr>
<tr class="odd">
<td># of People Served</td>
<td>3527</td>
<td>1,187,561</td>
<td>67,354,868</td>
<td>0</td>
<td>4.00e+09</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The next two variables in <a href="#tbl-nonprofits-descriptive-stats" class="quarto-xref">Table&nbsp;<span>2.2</span></a> are related to another feature of organizations that we can consider here: how large these nonprofit organizations are. How exactly shall we measure organizational size? There are many possibilities, but we will focus on three: (1) the number of employees, (2) the number of people served, and (3) how much money the organization spends. The measures available for the first two measures are regular quantitative variables, which is why they appear in <a href="#tbl-nonprofits-descriptive-stats" class="quarto-xref">Table&nbsp;<span>2.2</span></a>. We can see that the average organization has around 14 fulltime staff members, though there are organizations</p>
<p>For the third measure of size (organizational spending levels), the survey researchers have reported this variable only in “bins” (a concept we learned about in the prior chapter in the context of histograms). The researchers likely report the data in this way to protect the privacy of those responding to the survey.[^describing-one-variable-1] This effectively converts what was originally a quantitative variable into an ordinal variable. Ordinal variables can typically be treated as either quantitative or qualitative. For the present discussion, it is simpler to treat this variable as qualitative and show its distribution with a frequency table.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Revenue</th>
<th>Freq.</th>
<th>Percent</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>&lt;$100,000</td>
<td>641</td>
<td>15.80</td>
</tr>
<tr class="even">
<td>$100,000-$499,999</td>
<td>1,803</td>
<td>44.45</td>
</tr>
<tr class="odd">
<td>$500,000-$999,999</td>
<td>648</td>
<td>15.98</td>
</tr>
<tr class="even">
<td>$1 million-$9,999,999</td>
<td>861</td>
<td>21.23</td>
</tr>
<tr class="odd">
<td>$10 million and above</td>
<td>103</td>
<td>2.54</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Total</td>
<td>4,056</td>
<td>100.00</td>
</tr>
</tbody>
</table>
<p>Throughout this chapter, we will re-examine the variables and statistics shown above to further demonstrate key material for this chapter on describing variables one at a time. Before returning to the main chapter, though, it is worth briefly zooming out and making a few more observations about the big picture of this dataset, drawing on the Three Questions to Always Ask about Data.</p>
<ol start="2" type="1">
<li><p><strong>Who (or what) is in the dataset?</strong></p>
<p>The researchers conducting this survey provide a detailed description in one of their reports of the types of organizations that were excluded from the study. Particularly notable is the exclusion of very small organizations and many types of religious and educational organizations (such as most churches and schools). These are important things to know about the sample when trying to understand what portions of the nonprofit sector this data is describing.</p></li>
<li><p><strong>How big are the differences?</strong></p>
<p>One way to answer this question is to observe how highly varied nonprofit organizations appear to be in terms of size. There are many organizations that are very small and many others that are stunningly large by comparison. This is not a dataset describing a set of organizations with fairly uniform size. Describing the amount of “spread” or lack of uniformity in a variable is not a particularly easy or intuitive thing to do, but we will learn several tools to help us in this chapter.</p></li>
</ol>
</div>
</div>
<section id="essential-terms-and-concepts-for-describing-quantitative-variables" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="essential-terms-and-concepts-for-describing-quantitative-variables"><span class="header-section-number">2.1</span> Essential Terms and Concepts for Describing Quantitative Variables</h2>
<p>Several statistical terms can help us describe in words different characteristics we see in the distributions of quantitative variables. We can get familiar with these terms by looking at several histograms together and then describing their shapes.</p>
<p><a href="#fig-hist-er-cardio" class="quarto-xref">Figure&nbsp;<span>2.1</span></a> shows a histogram for a variable we will examine in more detail in <a href="prob-models.html" class="quarto-xref"><span>Chapter 7</span></a>. The distribution appears to be fairly <strong>symmetric</strong>: if we divided the graph with a vertical line at the midpoint, the two halves would roughly mirror each other.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> The peak of the distribution is called the <strong>mode</strong>. Since there is only one well-defined peak, we say that this distribution is <strong>unimodal</strong>. At each end of the graph (left and right), we see some fairly short bars that we refer to as the <strong>tails</strong> of the distribution.</p>
<div id="fig-hist-er-cardio" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-hist-er-cardio-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Images/describing-one-variable/hist-er-cardio.png" class="img-fluid figure-img" width="400">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-hist-er-cardio-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.1: Histogram of daily volume of cardiovascular ER admissions; data from <a href="https://doi.org/10.1371/journal.pone.0183224">Hwang et al.</a> (<a href="https://creativecommons.org/licenses/by/4.0/">CC-BY 4.0</a>)
</figcaption>
</figure>
</div>
<p>Our next histogram (<a href="#fig-hist-donations" class="quarto-xref">Figure&nbsp;<span>2.2</span></a>) depicts the variable measuring revenue from individual donations from our case study. This variable arguably has a unimodal distribution, since there is only one really well-defined peak (although one could argue that the right-most bar indicates a second, much smaller peak). However, this one is not symmetric. Instead, it is <strong>skewed</strong>. Specifically, it is <strong>skewed right</strong> because there is a long tail extending out to the right. The values far out in the tail are often referred to as <strong>outliers</strong>. Outliers refer to unusually small or large values in a distribution. Outliers can also be called <em>extreme values</em>. Note too that right skew can also be referred to as <strong>positive skew</strong>.</p>
<div id="fig-hist-donations" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-hist-donations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Images/describing-one-variable/hist-donations.png" class="img-fluid figure-img" width="400">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-hist-donations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.2: Histogram Based on Variable from Chapter Case Study
</figcaption>
</figure>
</div>
<p><a href="#fig-hist-females_publ-2" class="quarto-xref">Figure&nbsp;<span>2.3</span></a> (seen once already in the previous chapter) shows an example of <strong>left skew</strong>, also known as <strong>negative skew</strong>. Notice that there is a tail extending out to the left side of the graph (and toward the negative side of the number line), but no similar tail exists on the right.</p>
<div id="fig-hist-females_publ-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-hist-females_publ-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Images/getting-started/hist-female-employees.png" class="img-fluid figure-img" width="400">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-hist-females_publ-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.3: Histogram showing female employment by governments in different countries
</figcaption>
</figure>
</div>
<p>As one final example for this section, consider <a href="#fig-eruptionfreqs" class="quarto-xref">Figure&nbsp;<span>2.4</span></a>, which is a <strong>bimodal</strong> distribution, since there are two clear peaks apparent in the histogram. It is also possible to have more than two peaks, so we can generally refer to any distribution with more than one well-defined peak as <strong>multimodal</strong>.</p>
<div id="fig-eruptionfreqs" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-eruptionfreqs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Images/describing-one-variable/eruptionfreqs.jpg" class="img-fluid figure-img" width="400">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-eruptionfreqs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.4: Frequencies of times between eruptions of the Old Faithful geyser. Source: Lane &amp; Ziemer
</figcaption>
</figure>
</div>
</section>
<section id="sec-percentiles-and-box-plots" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="sec-percentiles-and-box-plots"><span class="header-section-number">2.2</span> Percentiles and Box Plots</h2>
<p>Percentiles are a powerful tool for describing a distribution. They are commonly used to help interpret standardized exam scores (e.g., university admissions exams). For example, you may have been told that you received a 139 on an exam and that this score indicates the 81st percentile, meaning you scored as good or better than 81% of people taking the exam.</p>
<p>We can further illustrate percentiles using the board size variable from this chapter’s case study. As we apply percentiles, we can think of dividing a dataset in two. <a href="#fig-hist-board-p50" class="quarto-xref">Figure&nbsp;<span>2.5</span></a> demonstrates this, using the 50th percentile to divide the observed values of board size into the bottom 50% and the top 50%. Each bar in this graph represents a single value, which is feasible because there are only whole numbers for this variable (you can’t have half a board member). The 50th percentile is 9 here, marked with a dashed line in the figure. 50% of these education nonprofits have boards that are 9 members or smaller. The relatively small boards with fewer than 9 members are shown with the bars drawn in a darker shade and labeled “Bottom 50%” in the legend at the bottom of <a href="#fig-hist-board-p50" class="quarto-xref">Figure&nbsp;<span>2.5</span></a>. The “Top 50%,” represented by bars in lighter shade, are larger than 9 members. Note that there are also some nonprofit boards with exactly 9 members, which are depicted with a white bar (with grey outline) because some (but not all) of these observations would be needed to get up to exactly 50% when delineating the bottom 50% or the top 50%. Because of these observation’s somewhat ambiguous status (being exactly equal to the 50th percentile), they are not shown in either dark or light shading.</p>
<div id="fig-hist-board-p50" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-hist-board-p50-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Images/describing-one-variable/hist-board-p50.png" class="img-fluid figure-img" width="400">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-hist-board-p50-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.5: Graphical Illustration of the 50th Percentile
</figcaption>
</figure>
</div>
<p>By using multiple percentiles simultaneously, we can divide a variable into more than two “buckets.” For example, we can divide this same variable into 3 buckets: the bottom 25%, the middle 50%, and the top 25%. This division is shown in <a href="#fig-hist-board-p25-p75" class="quarto-xref">Figure&nbsp;<span>2.6</span></a>. The divisions between “buckets” are marked with dashed lines, and each bucket uses different shading for the histogram’s bars.</p>
<div id="fig-hist-board-p25-p75" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-hist-board-p25-p75-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Images/describing-one-variable/hist-board-p25-p75.png" class="img-fluid figure-img" width="400">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-hist-board-p25-p75-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.6: Graphical Illustration of the 25th and 75th Percentiles
</figcaption>
</figure>
</div>
<p>Using the terminology of percentiles, we can say that the 25th percentile for this variable is 6, as indicated by the dashed line on the left. We can interpret this percentile as indicating that 25% of the boards have a size of 6 members or less. To mark the top 25% of the data, we use the 75th percentile, which is 13 for this variable. Thus, 75% of the education nonprofits in this dataset have boards with 13 or more members.</p>
<p>Box plots are a common way to visualize the percentiles we just discussed for a variable. <a href="#fig-boxplot-board" class="quarto-xref">Figure&nbsp;<span>2.7</span></a> shows a box plot for the board size variable. In a box plot, the edges of a rectangle depict the 25th and 75th percentiles. This corresponds exactly to the dashed lines we saw in the prior figure (<a href="#fig-hist-board-p25-p75" class="quarto-xref">Figure&nbsp;<span>2.6</span></a>). A line within the box also marks the 50th percentile.</p>
<div id="fig-boxplot-board" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-boxplot-board-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Images/describing-one-variable/boxplot-board.png" class="img-fluid figure-img" width="400">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-boxplot-board-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.7: Box Plot of Board Size Variable
</figcaption>
</figure>
</div>
<p>“Whiskers” extend out from the sides of the box to show the minimum and maximum values for the variable. Based on where the whiskers end, we can say that the smallest boards have 0 members while the largest have 22. However, 22 is not the true maximum. Notice the dots on the right side of the graph. These indicate outliers, which are often ignored for purposes of defining the minimum and maximum values when drawing the whiskers. Typically (though not always), outliers beyond the range of the whiskers are depicted using dots, as in this example. Various algorithms can be used to determine what exactly counts as an outlier, and most software will use one of these algorithms by default when creating a box plot.</p>
<p>Previously, while examining a histogram of this same variable, we noted that it is right-skewed. We can also see that here, based on the right-side whisker being somewhat longer than the left-side whisker, as well as the presence of outliers on the right side of the graph.</p>
<section id="defining-percentiles" class="level3" data-number="2.2.1">
<h3 data-number="2.2.1" class="anchored" data-anchor-id="defining-percentiles"><span class="header-section-number">2.2.1</span> Defining percentiles</h3>
<p>Now that we have seen some visualizations of percentiles, let’s define them a bit more precisely. The key thing to remember is this: <em>p</em>% of the data falls (at or) below the <em>p</em>th percentile. Thus, the <em>p</em>th percentile is a value indicating the point at which <em>p</em>% of the data is less than or equal to this value. <em>p</em> can be any number between 0 and 100. For example, if the 22nd percentile of a variable is 5, then 22% of the variable’s observations are less than or equal to 5. The flip side of this is that 78% of the variable’s observation must be greater than or equal to 5. Any percentile can be understood as marking a dividing line in a dataset, with <em>p</em>% of the data to the left and (100 - <em>p</em>)% to the right.</p>
<p>To find the <em>p</em>th percentile, we can line all the observations for a variable from least to greatest and then pick the value that marks the <em>p</em>% point in this lineup (e.g, for 50th percentile, pick the middle point). In practice, this process can get a bit complicated because we need rules to deal with ties, rounding, etc. There are, in fact, conflicting definitions of percentiles that employ different rules for such situations. If you are curious to learn more, this chapter contains an appendix with further details (Appendix I). Fortunately, these details are not essential for making use of percentiles to describe distributions. For the purposes of an introductory text, we can simply assume that software will make the exact computations needed to find percentiles under a widely-used definition. Slight differences in methods for computing percentiles will not usually affect our conclusions, at least if we are working with a large dataset where there are not large gaps in the values observed. Percentiles may be less useful/well-defined for describing datasets with very few observations (e.g., less than 50) or variables that take on only a small number of different values (e.g., only small whole numbers).</p>
</section>
<section id="box-plots-and-five-number-summaries" class="level3" data-number="2.2.2">
<h3 data-number="2.2.2" class="anchored" data-anchor-id="box-plots-and-five-number-summaries"><span class="header-section-number">2.2.2</span> Box plots and five number summaries</h3>
<p>As one additional example of a box plot, let’s examine the individual donations variable from this chapter’s case study. <a href="#fig-box-donations" class="quarto-xref">Figure&nbsp;<span>2.8</span></a> contains a box plot for this variable, and unlike the other box plots we’ve seen so far, this one has been drawn vertically. As we noted in an earlier section when examining a histogram, this variable is right-skewed, which we now see in the form of the long whisker and outliers at the top of the graph, since it is now the top of the graph that shows the highest values. There are dots depicting outliers, but they appear to be quite dense, sometimes overlapping and perhaps even stacking on top of one another. In cases like this, we can consider plotting the outliers in another way, such as using open circles and perhaps spreading them out a bit by adding some random “jitter” to their locations (as in the strip plot shown in the prior chapter).</p>
<div id="fig-box-donations" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-box-donations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Images/describing-one-variable/box-donations.png" class="img-fluid figure-img" width="400">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-box-donations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.8: Box Plot of Share of Revenue from Individual Donations
</figcaption>
</figure>
</div>
<p>You will likely encounter box plots that look quite different from the ones displayed in this chapter. While every box plot should start from drawing a box and whiskers, formating varies and extra features can be added to the plot. For example, people sometimes add a marking (such as an “X”) to indicate the mean for the variable. Sometimes it will also be the case that so many observations take on the same value that the minimum and the 25th percentile are the same, for example. This leads to a rather funny looking box plot since the whisker has a length of 0, meaning it essentially stacks on top of the edge of the box. If you try making your own box plots with software, you may encounter issues like this that make some box plots look very different from what you expected.</p>
<p>One common way of using percentiles to succinctly describe a distribution in table format is with a “five number summary.” This refers to the 0th, 25th, 50th, 75th, and 100th percentiles. In fact, that is exactly what a box plot shows, except that outliers are often omitted when drawing the whiskers in such plots. <a href="#tbl-five-number-summary" class="quarto-xref">Table&nbsp;<span>2.3</span></a> shows an alternative to the descriptive statistics table from this chapter’s case study, using the five number summary.</p>
<div id="tbl-five-number-summary" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-five-number-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2.3: Five Number Summary for Quantitative Variables from Chapter Case Study
</figcaption>
<div aria-describedby="tbl-five-number-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 34%">
<col style="width: 13%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Min. (p0)</th>
<th>p25</th>
<th>p50</th>
<th>p75</th>
<th>Max. (p100)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>% Rev.&nbsp;from Indv. Donations</td>
<td>0</td>
<td>5</td>
<td>15</td>
<td>40</td>
<td>100</td>
</tr>
<tr class="even">
<td># of Fulltime Staff</td>
<td>0</td>
<td>1</td>
<td>3</td>
<td>10</td>
<td>1600</td>
</tr>
<tr class="odd">
<td># of People Served</td>
<td>0</td>
<td>329</td>
<td>1,500</td>
<td>7,000</td>
<td>4.00e+09</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>To conclude this section, I highlight some interchangeable terminology that is important to know in the context of percentiles:</p>
<ul>
<li><p>The 0th percentile is the same as the <strong>minimum</strong>, or the smallest value observed for a variable.</p></li>
<li><p>The 100th percentile is the same as the <strong>maximum</strong>, or the largest value observed for a variable.</p></li>
<li><p>The 50th percentile is also called the <strong>median</strong>, as we will discuss in further detail in the following section.</p></li>
<li><p>The five number summary suggest a division of the data into four “buckets.” These four buckets are known as <strong>quartiles</strong>.</p></li>
</ul>
</section>
</section>
<section id="measures-of-central-tendency" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="measures-of-central-tendency"><span class="header-section-number">2.3</span> Measures of Central Tendency</h2>
<p>With measures of central tendency, we seek to identify a single number that helps answer the question “What is the typical value for this variable?”</p>
<p>The most common measure of central tendency is the <strong>mean</strong>, which is what we typically mean when we say the “average.” To calculate the mean, we simply add up all the values appearing for a variable and then divide by the number of observations.</p>
<p>A common alternative to the mean is the <strong>median</strong>. As noted in the prior section, the median is also the 50th percentile. To identify the median, we can line up all observations from least to greatest (according to the variable of interest) and then pick the value in the very middle. If two values are tied (i.e., there is an even number of observations), we take the average of the two tied values.</p>
<p>A third measure of central tendency is the <strong>mode</strong>. This is the value that occurs most often.</p>
<p>How do we choose among these three measures of central tendency? The ideal measure usually depends on the data and the purpose of the analysis.</p>
<p>For qualitative data, only the mode is available. There is no way to calculate a mean or median for a qualitative variable (although people sometimes accidentally do so if they have used numbers to code the variable within a spreadsheet).</p>
<p>For quantitative variables, the mode is sometimes a reasonable option but not always. It largely depends on the specific type of quantitative variable. <em>Continuous</em> variables are reported to many digits (usually with decimal places), so it is rare to see the same value repeating very often if at all. As such, the mode is a poor measure of central tendency for continuous variables. For <em>discrete</em> variables, which typically take on whole numbers, the mode can be more appropriate. For example, the mode is a perfectly reasonable measure of central tendency for a variable measuring the number of people in a household.</p>
<p>There is still a way to make use of the mode for continuous variables. It requires using “bins,” as we do whenever we create a histogram. When we refer to the peak or tallest bar in a histogram as the mode, we are identifying the bin with the range of values that occur most often.</p>
<p>If we are examining a quantitative variable and do not want outliers to have too much influence on our measure of central tendency, then the median is often the preferred option. This is because mean is highly sensitive to outliers, while the median is not. Consider the quantitative measures of organizational size from this chapter’s case study. The values of the mean shown in our initial descriptive statistics table turn out to be rather poor summaries of these variables for most purposes. This is especially true for the variable indicating the number of people served, where an extreme outlier hugely influences the mean: one organization indicates that it has served 2 billion people. The contrast between the median (percentile) based description in <a href="#tbl-five-number-summary" class="quarto-xref">Table&nbsp;<span>2.3</span></a> and the original descriptive table (<a href="#tbl-nonprofits-descriptive-stats" class="quarto-xref">Table&nbsp;<span>2.2</span></a>) is stark for this variable, as well as the variable indicating number of employees.</p>
<p>For variables where there are no big outliers or where the distribution is symmetric (and thus the outliers are balanced between the left and right tails), the mean and the median usually yield similar values. In right-skewed distributions, the mean is typically larger (to the “right” of) the median. This matches the description provided above for the quantitative size variables from our case study. For left-skewed distributions, the mean is typically to the left of the median.</p>
<p>Given concerns about outliers, you will find that the median is often used to describe variables like income or size that may be highly right-skewed.</p>
<p>Sometimes, however, the mean’s sensitivity to outliers is a strength. If we are trying to run a business and need to make sure that subscription revenues for a maintenance will cover the costs, we will probably want to compare average revenue per subscriber to average costs. If one in every 100 subscribers requires help that costs many multiples of the ordinary subscriber, we will need to price the subscription to cover these “outlier” expenses. Relying on median costs to set the price of subscriptions could yield disastrous results, since the outliers cases could cost so much that they wipe out our earnings from all the typical customers.</p>
<p>The mean is also often an attractive option when summarizing certain ordinal variables, like those commonly resulting from use of Likert scales. Such variables will not have large outliers, and the median will often not respond to relatively subtle but potentially important differences in response pattern. For example, suppose employees from two different companies respond to a survey where they respond to a question asking how satisfied they are at work. If 90% of respondents in company A select “very satisfied” (the top response option) while only 60% select “very satisfied” in company B, median satisfaction for both companies will be the same, but the mean will be higher in company A.</p>
<p>Given that both the mean and the median have clear advantages and clear drawbacks, some sources recommend reporting both statistics whenever describing the central tendency of a variable. This is probably a good rule of thumb to start from, and with experience you can figure out when one statistics or the other is more useful depending on the data and the broader context of your analysis.</p>
</section>
<section id="measures-of-spreaddescribing-one-variable-2" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="measures-of-spreaddescribing-one-variable-2"><span class="header-section-number">2.4</span> Measures of Spread<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></h2>
<p>Spread refers to how “spread out” a group of scores is. To see what we mean by spread out, consider <a href="#fig-quiz-1" class="quarto-xref">Figure&nbsp;<span>2.9</span></a> and <a href="#fig-quiz-2" class="quarto-xref">Figure&nbsp;<span>2.10</span></a>. These graphs represent the scores on two quizzes. The mean score for each quiz is 7.0. Despite the equality of means, you can see that the distributions are quite different. Specifically, the scores on Quiz 1 are more densely packed and those on Quiz 2 are more spread out. The differences among students were much greater on Quiz 2 than on Quiz 1.</p>
<div id="fig-quiz-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-quiz-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Images/describing-one-variable/Quiz1.jpg" class="img-fluid figure-img" width="425">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-quiz-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.9: Quiz 1
</figcaption>
</figure>
</div>
<div id="fig-quiz-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-quiz-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Images/describing-one-variable/Quiz2.jpg" class="img-fluid figure-img" width="425">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-quiz-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.10: Quiz 2
</figcaption>
</figure>
</div>
<p>Measures of spread help us answer the question “How tightly is the data clustered around the center of the distribution?” Or if we wish to more specifically reference a measure of central tendency, we might ask “Are most observed values for this variable pretty close to its mean/median?”</p>
<p>The simplest measure of central tendency is the <strong>range</strong>. The range is the difference between a variable’s minimum and maximum value. Sometimes it is expressed as a single number (e.g., if the minimum is 100 and the maximum is 300, the range is 200 since 300 - 100 = 200). Other times, it is described as the interval defined by the minimum and maximum (e.g., 100 to 300). While the range has the benefit of being simple and intuitive, it is sensitive to outliers and tells us little about whether the typical value lies close to the mean/median.</p>
<p>One should also exercise great caution in using the range to make comparisons. The range can be sensitive to sample size: a larger sample offers greater opportunity for the range to expand. If one is comparing males to females and has equally-sized samples for each sex, comparing the range among female for some variable to its range among men may be reasonable. However, if we were to compare two samples with different numbers of observations, then the range is not necessarily a good way to compare the spreads of the samples.</p>
<p>Another measure of spread is the <strong>interquartile range (IQR)</strong>, which refers to the difference between the 75th and 25th percentile. The IQR is depicted as the length of the “box” when we draw a box plot. When the IQR is larger, it indicates that the middle 50% of the data is spread out over a larger range of values.</p>
<p>The most common measures of spread are <strong>variance</strong> and <strong>standard deviation</strong>. The formula for variance is provided in Appendix II. It is based on observing how far each and every value is from the average value. If the mean is 52 and most observations are very close to this average (e.g., most observations are in the range of 51 to 53), the variance will be quite small. If many observations have values that are quite far from the average (e.g., many observations are as low as in the 20s and and high as in the 80s), the variance will be quite large. To be precise, the calculation of variance is based on finding the average squared distance between each observation and the mean.</p>
<p>Standard deviation is closely related to variance: you simply take the square root of the variance to find the standard deviation. Since variance is based on squared distance from the mean, taking the square root at the end gets us back to our original units in some sense. Therefore, we can interpret the standard deviation of X as approximating the typical distance between a given value of X and the mean of X. For example, suppose I tell you about a prison where the prisoners have a mean age of 42 years with a standard deviation of 8 years. If I randomly select one prisoner and ask you to guess their age, you should probably guess 42 since I’ve told you that is the mean. But even though 42 is your best guess, you can expect your guess to be off by about 8 years since the standard deviation is 8 (meaning the typical distance between a random prisoner’s age and the mean age is approximately 8). You can’t say ahead of time which direction your guess is likely to be off (guessing too old versus too young), just that you are likely to miss the reality for a randomly-selected individual by about 8 years on a typical guess (though any one guess may happen to be closer or further than 8 years).</p>
<p>The concept of spread can also be referred to as <em>variability</em> or <em>dispersion</em>. We can also say that large spread indicates high <strong>heterogeneity</strong>, meaning that units tend not to closely resemble one another. On the flip side, a small spread indicates that for the variable being examined, observations are highly <strong>homogeneous</strong> or highly uniform.</p>
</section>
<section id="exercisesdescribing-one-variable-3" class="level2" data-number="2.5">
<h2 data-number="2.5" class="anchored" data-anchor-id="exercisesdescribing-one-variable-3"><span class="header-section-number">2.5</span> Exercises<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></h2>
<ol type="1">
<li><p>Find the mean and median for the following three variables:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>A</th>
<th>B</th>
<th>C</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>8</td>
<td>4</td>
<td>6</td>
</tr>
<tr class="even">
<td>5</td>
<td>4</td>
<td>2</td>
</tr>
<tr class="odd">
<td>7</td>
<td>6</td>
<td>3</td>
</tr>
<tr class="even">
<td>1</td>
<td>3</td>
<td>4</td>
</tr>
<tr class="odd">
<td>3</td>
<td>4</td>
<td>1</td>
</tr>
</tbody>
</table></li>
<li><p>You recorded the time in seconds it took for 8 participants to solve a puzzle. These times appear below. However, when the data was entered into the statistical program, the score that was supposed to be 22.1 was entered as 21.2. You had calculated the following measures of central tendency: the mean and the median. Which of these measures of central tendency will change when you correct the recording error?</p>
<p>15.2<br>
18.8<br>
19.3<br>
19.7<br>
20.2<br>
21.8<br>
22.1<br>
29.4</p></li>
<li><p>For the scores in the prior question, which measures of variability (range, standard deviation, variance) would be changed if the 22.1 data point had been erroneously recorded as 21.2?</p></li>
<li><p>You know the minimum, the maximum, and the 25th, 50th, and 75th percentiles of a distribution. Which of the following measures of central tendency or variability can you determine? mean, median, mode, range, interquartile range, variance, standard deviation</p></li>
<li><p>A sample of 30 distance scores measured in yards has a mean of 7, a variance of 16, and a standard deviation of 4. (a) You want to convert all your distances from yards to feet, so you multiply each score in the sample by 3. What are the new mean, variance, and standard deviation? (b) You then decide that you only want to look at the distance past a certain point. Thus, after multiplying the original scores by 3, you decide to subtract 4 feet from each of the scores. Now what are the new mean, variance, and standard deviation?</p></li>
<li><p>Your younger brother comes home one day after taking a science test. He says that someone at school told him that “60% of the students in the class scored above the median test grade.” What is wrong with this statement? What if he said “60% of the students scored below the mean?”</p></li>
<li><p>If the mean time to respond to a stimulus is much higher than the median time to respond, what can you say about the shape of the distribution of response times?</p></li>
<li><p>An experiment compared the ability of three groups of participants to remember briefly-presented chess positions. The data are shown below. The numbers represent the total number of pieces correctly remembered from three chess positions. Create side-by-side box plots for these three groups. What can you say about the differences between these groups from the box plots?</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Non-players</th>
<th>Beginners</th>
<th>Tournament players</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>22.1</td>
<td>32.5</td>
<td>40.1</td>
</tr>
<tr class="even">
<td>22.3</td>
<td>37.1</td>
<td>45.6</td>
</tr>
<tr class="odd">
<td>26.2</td>
<td>39.1</td>
<td>51.2</td>
</tr>
<tr class="even">
<td>29.6</td>
<td>40.5</td>
<td>56.4</td>
</tr>
<tr class="odd">
<td>31.7</td>
<td>45.5</td>
<td>58.1</td>
</tr>
<tr class="even">
<td>33.5</td>
<td>51.3</td>
<td>71.1</td>
</tr>
<tr class="odd">
<td>38.9</td>
<td>52.6</td>
<td>74.9</td>
</tr>
<tr class="even">
<td>39.7</td>
<td>55.7</td>
<td>75.9</td>
</tr>
<tr class="odd">
<td>43.2</td>
<td>55.9</td>
<td>80.3</td>
</tr>
<tr class="even">
<td>43.2</td>
<td>57.7</td>
<td>85.3</td>
</tr>
</tbody>
</table></li>
<li><p>In a box plot, what percent of the scores are between the lower and upper hinges?</p></li>
<li><p>Which of the box plots in <a href="#fig-boxplots-exercises" class="quarto-xref">Figure&nbsp;<span>2.11</span></a> has a large positive skew? Which has a large negative skew?</p>
<div id="fig-boxplots-exercises" class="quarto-float quarto-figure quarto-figure-center anchored" width="170">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-boxplots-exercises-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Images/describing-one-variable/boxplots_exercises.png" id="fig-boxplots-exercises" class="img-fluid figure-img" width="170">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-boxplots-exercises-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.11
</figcaption>
</figure>
</div></li>
<li><p>When is a log transformation valuable?</p></li>
</ol>
</section>
<section id="sec-describing-one-variable-appendix-i-calculating-percentilesdescribing-one-variable-4" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="sec-describing-one-variable-appendix-i-calculating-percentilesdescribing-one-variable-4"><a href="#sec-describing-one-variable" class="quarto-xref"><span>Chapter 2</span></a> Appendix I: Calculating Percentiles<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></h2>
<p>There is no universally accepted definition of a percentile. Using the 65th percentile as an example, the 65th percentile can be defined as the lowest score that is greater than 65% of the scores. We will call this “Definition 1.” The 65th percentile can also be defined as the smallest score that is greater than <em>or equal to</em> 65% of the scores. This we will call “Definition 2.” Though these two definitions appear very similar, they can sometimes lead to dramatically different results, especially when there is relatively little data. Moreover, neither of these definitions is explicit about how to handle rounding. For instance, what rank is required to be higher than 65% of the scores when the total number of scores is 50? This is tricky because 65% of 50 is 32.5. How do we find the lowest number that is higher than 32.5 of the scores?</p>
<p>A third way to compute percentiles is a weighted average of the percentiles computed according to the first two definitions. The details of computing percentiles under this third definition are a bit complicated. Let’s begin with an example. Consider the 25th percentile for the 8 numbers in <a href="#tbl-numberrankscores" class="quarto-xref">Table&nbsp;<span>2.4</span></a>. Notice the numbers are given ranks ranging from 1 for the lowest number to 8 for the highest number.</p>
<div id="tbl-numberrankscores" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-numberrankscores-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2.4: Test Scores.
</figcaption>
<div aria-describedby="tbl-numberrankscores-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 18%">
<col style="width: 12%">
<col style="width: 15%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th><strong>Number</strong></th>
<th></th>
<th><strong>Rank</strong></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td>3<br>
5<br>
7<br>
8<br>
9<br>
11<br>
13<br>
15</td>
<td></td>
<td>1<br>
2<br>
3<br>
4<br>
5<br>
6<br>
7<br>
8</td>
<td></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The first step is to compute the rank (<span class="math inline">\(R\)</span>) of the 25th percentile. This is done using the following formula:</p>
<p><span class="math display">\[
R = P/100 \times (N + 1)
\]</span></p>
<p>where <span class="math inline">\(P\)</span> is the desired percentile (25 in this case) and <span class="math inline">\(N\)</span> is the number of numbers (8 in this case). Therefore,</p>
<p><span class="math display">\[
R = 25/100 \times (8 + 1) = 9/4 = 2.25.
\]</span></p>
<p>If <span class="math inline">\(R\)</span> is an integer, the <span class="math inline">\(Pth\)</span> percentile is the number with rank <span class="math inline">\(R\)</span>. When <span class="math inline">\(R\)</span> is not an integer, we compute the <span class="math inline">\(Pth\)</span> percentile by interpolation as follows:</p>
<ol type="1">
<li><p>Define <span class="math inline">\(IR\)</span> as the integer portion of <span class="math inline">\(R\)</span> (the number to the left of the decimal point). For this example, <span class="math inline">\(IR\)</span> = 2.</p></li>
<li><p>Define <span class="math inline">\(FR\)</span> as the fractional portion of <span class="math inline">\(R\)</span>. For this example, <span class="math inline">\(FR\)</span> = 0.25.</p></li>
<li><p>Find the scores with Rank <span class="math inline">\(IR\)</span> and with Rank <span class="math inline">\(IR\)</span> + 1. For this example, this means the score with Rank 2 and the score with Rank 3. The scores are 5 and 7.</p></li>
<li><p>Interpolate by multiplying the difference between the scores by <span class="math inline">\(FR\)</span> and add the result to the lower score. For these data, this is (0.25)(7 - 5) + 5 = 5.5.</p></li>
</ol>
<p>Therefore, the 25th percentile is 5.5. If we had used the first definition (the smallest score greater than 25% of the scores), the 25th percentile would have been 7. If we had used the second definition (the smallest score greater than or equal to 25% of the scores), the 25th percentile would have been 5.</p>
<p>For a second example, consider the 20 quiz scores shown in <a href="#tbl-quizscores" class="quarto-xref">Table&nbsp;<span>2.5</span></a>.</p>
<div id="tbl-quizscores" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-quizscores-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2.5: 20 quiz scores.
</figcaption>
<div aria-describedby="tbl-quizscores-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 16%">
<col style="width: 12%">
<col style="width: 15%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th><strong>Score</strong></th>
<th></th>
<th><strong>Rank</strong></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td>4<br>
4<br>
5<br>
5<br>
5<br>
5<br>
6<br>
6<br>
6<br>
7<br>
7<br>
7<br>
8<br>
8<br>
9<br>
9<br>
9<br>
10<br>
10<br>
10</td>
<td></td>
<td>1<br>
2<br>
3<br>
4<br>
5<br>
6<br>
7<br>
8<br>
9<br>
10<br>
11<br>
12<br>
13<br>
14<br>
15<br>
16<br>
17<br>
18<br>
19<br>
20</td>
<td></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>We will compute the 25th and the 85th percentiles. For the 25th,</p>
<p><span class="math display">\[
R = 25/100 \times (20 + 1) = 21/4 = 5.25.
\]</span></p>
<p><span class="math display">\[
IR = 5 \text{ and } FR = 0.25.
\]</span></p>
<p>Since the score with a rank of <span class="math inline">\(IR\)</span> (which is 5) and the score with a rank of <span class="math inline">\(IR\)</span> + 1 (which is 6) are both equal to 5, the 25th percentile is 5. In terms of the formula:</p>
<p><span class="math display">\[
\text{ 25th percentile } = (.25) \times (5 - 5) + 5 = 5.
\]</span></p>
<p>For the 85th percentile,</p>
<p><span class="math display">\[
R = 85/100 \times (20 + 1) = 17.85.
\]</span></p>
<p><span class="math display">\[
IR = 17 \text{ and } FR = 0.85
\]</span></p>
<blockquote class="blockquote">
<p>Caution: <span class="math inline">\(FR\)</span> does not generally equal the percentile to be computed as it does here.</p>
</blockquote>
<p>The score with a rank of 17 is 9 and the score with a rank of 18 is 10. Therefore, the 85th percentile is:</p>
<p><span class="math display">\[
(0.85)(10 - 9) + 9 = 9.85
\]</span></p>
<p>Consider the 50th percentile of the numbers 2, 3, 5, 9.</p>
<p><span class="math display">\[
R = 50/100 \times (4 + 1) = 2.5.
\]</span></p>
<p><span class="math display">\[
IR = 2 \text{ and } FR = 0.5.
\]</span></p>
<p>The score with a rank of <span class="math inline">\(IR\)</span> is 3 and the score with a rank of <span class="math inline">\(IR\)</span> + 1 is 5. Therefore, the 50th percentile is:</p>
<p><span class="math display">\[
(0.5)(5 - 3) + 3 = 4.
\]</span></p>
<p>Finally, consider the 50th percentile of the numbers 2, 3, 5, 9, 11.</p>
<p><span class="math display">\[
R = 50/100 \times (5 + 1) = 3.
\]</span></p>
<p><span class="math display">\[
IR = 3 \text{ and } FR = 0.
\]</span></p>
<p>Whenever <span class="math inline">\(FR\)</span> = 0, you simply find the number with rank <span class="math inline">\(IR\)</span>. In this case, the third number is equal to 5, so the 50th percentile is 5. You will also get the right answer if you apply the general formula:</p>
<p><span class="math display">\[
\text{ 50th percentile }= (0.00) (9 - 5) + 5 = 5.
\]</span></p>
</section>
<section id="sec-describing-one-variable-appendix-ii-formulas-for-calculating-key-descriptive-statistics" class="level2" data-number="2.6">
<h2 data-number="2.6" class="anchored" data-anchor-id="sec-describing-one-variable-appendix-ii-formulas-for-calculating-key-descriptive-statistics"><span class="header-section-number">2.6</span> <a href="#sec-describing-one-variable" class="quarto-xref"><span>Chapter 2</span></a> Appendix II: Formulas for Calculating Key Descriptive Statistics</h2>
<section id="meandescribing-one-variable-5" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="meandescribing-one-variable-5">Mean<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a></h3>
<p>The mean<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a> is simply the sum of the numbers divided by the number of numbers. When using symbols and formulas to represent different statistics, we often distinguish between whether we are looking at a “sample” or a “population.” We’ll cover this distinction in more detail in <a href="stat-inference.html" class="quarto-xref"><span>Chapter 5</span></a>. For now, think of a pollster who has conducted a survey with a sample of 1000 people. Even though only 1000 people responded to the survey, the pollster is actually interested in estimating the attitudes of a larger population—the entire public.</p>
<p>The symbol <span class="math inline">\(\mu\)</span> is used for the mean of a population. The symbol <span class="math inline">\(\bar{x}\)</span> is used for the mean of a sample. The formula for <span class="math inline">\(\mu\)</span> is shown below:</p>
<p><span class="math display">\[
\mu = \frac{\sum_{i=1}^{N} x_i}{N}
\]</span></p>
<p>where <span class="math inline">\(\sum_{i=1}^{N} x_i\)</span> is the sum of all the numbers in the population and <span class="math inline">\(N\)</span> is the number of numbers in the population. Note that the summation syntax <span class="math inline">\(\sum_{i=1}^{N}\)</span> indicates that we begin at <span class="math inline">\(i=1\)</span> and repeatedly increase the value of our counter <span class="math inline">\(i\)</span> by 1 until we get to <span class="math inline">\(N\)</span>. Each time, we take <span class="math inline">\(x_i\)</span>, which refers to the <span class="math inline">\(i\)</span>th observation of the variable <span class="math inline">\(x\)</span>, and that is the value we add to the running list of values to sum.</p>
<p>The formula for <span class="math inline">\(\bar{x}\)</span> is essentially identical:</p>
<p><span class="math display">\[
\bar{x} = \frac{\sum_{i=1}^{n} x_i}{n}
\]</span></p>
<p>where <span class="math inline">\(\sum_{i=1}^{n} x_i\)</span> is the sum of all the numbers in the sample and <span class="math inline">\(n\)</span> is the number of numbers in the sample.</p>
<p>As an example, the mean of the numbers 1, 2, 3, 6, 8 is 20/5 = 4 regardless of whether the numbers constitute the entire population or just a sample from the population.</p>
<p><a href="#tbl-tdownpasses" class="quarto-xref">Table&nbsp;<span>2.6</span></a> shows the number of touchdown (TD) passes thrown by each of the 31 teams in the National Football League in the 2000 season. The mean number of touchdown passes thrown is 20.4516 as shown below.</p>
<p><span class="math display">\[
\mu = \frac{\sum_{i=1}^{N} x_i}{N} = \frac{634}{31} = 20.4516
\]</span></p>
<div id="tbl-tdownpasses" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-tdownpasses-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2.6: Number of touchdown passes.
</figcaption>
<div aria-describedby="tbl-tdownpasses-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 9%">
<col style="width: 80%">
<col style="width: 9%">
</colgroup>
<tbody>
<tr class="odd">
<td></td>
<td>37 33 33 32 29 28 28 23 22 22 22 21 21 21 20 20 19 19 18 18 18 18 16 15 14 14 14 12 12 9 6</td>
<td></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="variancedescribing-one-variable-7" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="variancedescribing-one-variable-7">Variance<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a></h3>
<p>Using the mean as the measure of the middle of the distribution, the variance is defined as the average squared difference of the scores from the mean. The data from Quiz 1 are shown in <a href="#tbl-quiz1var" class="quarto-xref">Table&nbsp;<span>2.7</span></a>. The mean score is 7.0. Therefore, the column “Deviation from Mean” contains the score minus 7. The column “Squared Deviation” is simply the previous column squared.</p>
<div id="tbl-quiz1var" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-quiz1var-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2.7: Calculation of Variance for Quiz 1 scores.
</figcaption>
<div aria-describedby="tbl-quiz1var-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 8%">
<col style="width: 12%">
<col style="width: 8%">
<col style="width: 25%">
<col style="width: 8%">
<col style="width: 23%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th><strong>Scores</strong></th>
<th></th>
<th><strong>Deviation from Mean</strong></th>
<th></th>
<th><strong>Squared Deviation</strong></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td>9</td>
<td></td>
<td>2</td>
<td></td>
<td>4</td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>9</td>
<td></td>
<td>2</td>
<td></td>
<td>4</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td>9</td>
<td></td>
<td>2</td>
<td></td>
<td>4</td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>8</td>
<td></td>
<td>1</td>
<td></td>
<td>1</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td>8</td>
<td></td>
<td>1</td>
<td></td>
<td>1</td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>8</td>
<td></td>
<td>1</td>
<td></td>
<td>1</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td>8</td>
<td></td>
<td>1</td>
<td></td>
<td>1</td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>7</td>
<td></td>
<td>0</td>
<td></td>
<td>0</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td>7</td>
<td></td>
<td>0</td>
<td></td>
<td>0</td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>7</td>
<td></td>
<td>0</td>
<td></td>
<td>0</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td>7</td>
<td></td>
<td>0</td>
<td></td>
<td>0</td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>7</td>
<td></td>
<td>0</td>
<td></td>
<td>0</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td>6</td>
<td></td>
<td>-1</td>
<td></td>
<td>1</td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>6</td>
<td></td>
<td>-1</td>
<td></td>
<td>1</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td>6</td>
<td></td>
<td>-1</td>
<td></td>
<td>1</td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>6</td>
<td></td>
<td>-1</td>
<td></td>
<td>1</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td>6</td>
<td></td>
<td>-1</td>
<td></td>
<td>1</td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>6</td>
<td></td>
<td>-1</td>
<td></td>
<td>1</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td>5</td>
<td></td>
<td>-2</td>
<td></td>
<td>4</td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>5</td>
<td></td>
<td>-2</td>
<td></td>
<td>4</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td><strong>Means</strong></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>7</td>
<td></td>
<td>0</td>
<td></td>
<td>1.5</td>
<td></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>One thing that is important to notice is that the mean deviation from the mean is 0. This will always be the case. The mean of the squared deviations is 1.5. Therefore, the variance is 1.5. Analogous calculations with Quiz 2 show that its variance is 6.7. The formula for the variance is:</p>
<p><span class="math display">\[
\sigma^2=\frac{\sum_{i=1}^{N} (x_i-\mu)^2}{N}
\]</span></p>
<p>where <span class="math inline">\(\sigma^2\)</span> is the variance, <span class="math inline">\(\mu\)</span> is the mean, and <span class="math inline">\(N\)</span> is the number of numbers. For Quiz 1, <span class="math inline">\(\mu\)</span> = 7 and <span class="math inline">\(N\)</span> = 20.</p>
<p>If the variance in a sample is used to estimate the variance in a population, then the previous formula underestimates the variance and the following formula should be used:</p>
<p><span class="math display">\[
s^2=\frac{\sum_{i=1}^{n}(x_i-\bar{x})^2}{n-1}
\]</span></p>
<p>where <span class="math inline">\(s^2\)</span> is the estimate of the variance and <span class="math inline">\(\bar{x}\)</span> is the sample mean.</p>
<p>Note that <span class="math inline">\(\bar{x}\)</span> is the mean of a sample taken from a population with a mean of <span class="math inline">\(\mu\)</span>. Since, in practice, the variance is usually computed in a sample, this formula is most often used. While it is not easy to succinctly explain why we divide by <span class="math inline">\(n-1\)</span> rather than simply <span class="math inline">\(n\)</span>, the simulation “estimating variance”<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a> illustrates the bias that arises if we use <span class="math inline">\(n\)</span> as the denominator in the formula.</p>
<p>Let’s look at a concrete example of calculating the sample variance. Assume the scores 1, 2, 4, and 5 were sampled from a larger population. To estimate the variance in the population you would compute <span class="math inline">\(s^2\)</span> as follows:</p>
<p><span class="math display">\[
\bar{x} = (1 + 2 + 4 + 5)/4 = 12/4 = 3
\]</span></p>
<p><span class="math display">\[
s^2 = [(1-3)^2 + (2-3)^2 + (4-3)^2 + (5-3)^2]/(4-1)
\]</span><span class="math display">\[
= (4 + 1 + 1 + 4)/3 = 10/3 = 3.333
\]</span></p>
<p>As noted in the main text, the standard deviation is simply the square root of the variance. This makes the standard deviations of the two quiz distributions 1.225 and 2.588.</p>


</section>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p><a href="https://datacatalog.worldbank.org/search/dataset/0037712/world-development-indicators">World Development Indicators</a> (<a href="https://datacatalog.worldbank.org/public-licenses?fragment=cc">CC-BY 4.0</a>)<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>The first pargraph and initial graphs in this section are adapted from David M. Lane. “Measures of Variability.” <em>Online Statistics Education: A Multimedia Course of Study</em>. <a href="https://onlinestatbook.com/2/summarizing_distributions/variability.html" class="uri">https://onlinestatbook.com/2/summarizing_distributions/variability.html</a><a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>More specifically, the arithmetic mean is the most common measure of central tendency. Although the arithmetic mean is not the only “mean” (there is also a geometric mean), it is by far the most commonly used. Therefore, if the term “mean” is used without specifying whether it is the arithmetic mean, the geometric mean, or some other mean, it is assumed to refer to the arithmetic mean.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>This section is adapted from David M. Lane. “Percentiles.” <em>Online Statistics Education: A Multimedia Course of Study</em>. <a href="https://onlinestatbook.com/2/introduction/percentiles.html" class="uri">https://onlinestatbook.com/2/introduction/percentiles.html</a><a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>This section is adapted from David M. Lane. “Measures of Central Tendency.” <em>Online Statistics Education: A Multimedia Course of Study</em>. <a href="https://onlinestatbook.com/2/summarizing_distributions/measures.html" class="uri">https://onlinestatbook.com/2/summarizing_distributions/measures.html</a><a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>More specifically, the arithmetic mean is the most common measure of central tendency. Although the arithmetic mean is not the only “mean” (there is also a geometric mean), it is by far the most commonly used. Therefore, if the term “mean” is used without specifying whether it is the arithmetic mean, the geometric mean, or some other mean, it is assumed to refer to the arithmetic mean.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>This section is adapted from David M. Lane. “Measures of Variability.” <em>Online Statistics Education: A Multimedia Course of Study</em>. <a href="https://onlinestatbook.com/2/summarizing_distributions/variability.html" class="uri">https://onlinestatbook.com/2/summarizing_distributions/variability.html</a><a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p><a href="https://onlinestatbook.com/2/summarizing_distributions/variance_est.html" class="uri">https://onlinestatbook.com/2/summarizing_distributions/variance_est.html</a><a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./getting-started.html" class="pagination-link" aria-label="Getting Started with Data">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Getting Started with Data</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./correlation.html" class="pagination-link" aria-label="Relationships Between Two Quantitative Variables">
        <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Relationships Between Two Quantitative Variables</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>